apiVersion: v1
kind: Service
metadata:
  name: binarycalculator-service
spec:
  selector:
    app: binarycalculator
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
